config/routes.rb
Rails.application.routes.draw do

  get 'master/show'

  root              'static_pages#home'
  get     'about'      =>  'static_pages#about'
  get     'signup'     =>  'users#new'
  get     'login'      =>  'sessions#new'
  post    'login'      =>  'sessions#create'
  delete  'logout'     =>  'sessions#destroy'
  get     'noaccount'  =>  'static_pages#noaccount'
  get     'new_home'   =>  'new_static_pages#home'

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :equipment_type
  resources :brands
  resources :equipment
  resources :hospitals
  resources :subareas
  resources :areas
  resources :hospitals do
    resources :floors, only: [] do
      get :areas_select, on: :member
    end
    resources :areas, only: [] do
      get :subareas_select, on: :member
    end
    resources :floors do
      resources :areas
    end
    resources :areas
    resources :equipment do
      get 'label' => 'equipment#label'
    end
    resources :equipment_type
    resources :brands
    resources :areas do
      resources :contacts
      resources :subareas
    end
    resources :contacts
  end
  resources :plans, only: [:index]
  resources :master do
    resources :plans
    resources :accounts
  end
  resources :accounts
  resources :contacts
  resources :plans do
    resources :hospitals,  only: [ :new, :create ] do
      resources :users,     only: [ :new, :create ] do
        resources :accounts,  only: [ :new, :create ]
      end
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  belongs_to :hospital
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :subareas
	belongs_to :hospital
	has_one :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :equipment
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :area
	belongs_to :hospital

	def area_name
		area.name
	end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :equipment_type
	belongs_to :brand
	belongs_to :hospital
	belongs_to :subarea
	mount_uploader :image, ImageUploader

	def brand_name
		brand.name
	end

	def subarea_name
		subarea.name
	end

	def equipment_type_name
		equipment_type.name
	end

	def cuadro_basico
		equipment_type.cuadro_basico
	end

	def umdns
		equipment_type.umdns
	end

	def gmnd
		equipment_type.gmnd
	end
end

app/models/equipment_type.rb
class EquipmentType < ActiveRecord::Base
	has_many :equipment
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	has_one :account
	has_many :users
	has_many :equipments
	has_many :areas
	has_many :contacts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :account
end

app/models/subarea.rb
class Subarea < ActiveRecord::Base
	belongs_to :area
	has_many :equipments

	def area_name
		area.name
	end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token
  before_save :downcase_email
  belongs_to :account
  belongs_to :hospital
  before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  												                        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, remember_token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  		redirect_to user_path(current_user)
    else
      render :layout => "home_layout"
    end
  end

  def about
  end

  def complete
  	@user = User.first
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end     
  end

  def logged_in?
    !current_user.nil?    
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Porfavor inicie seción"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def master_user
		redirect_to(root_url) unless current_user.user_type == "master"
	end

	def master_user?
		current_user.user_type == "master"
	end
end

app/views/static_pages/about.html.erb
<%= provide(:title, "Acerca") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<%= provide(:title, "Gestiona tu equipo médico" ) %>
  
  <div class="section hero">
    <div class="w-container">
      <h1 class="hero-heading">Cuida tú equipo médico, simple</h1>
      <p class="hero-subhead">Sinapsis te ayuda a que tengas tu equipo médico listo para el cuidado de la salud de tus pacientes.</p>
      <div class="button-group">
      <%= link_to "Entrar", login_path, class: "nav-link sign-up" %>
      <%= link_to "Registrate", plans_path, class: "button", style:"background-color: #DD6922;" %>
      </div>
      <%= image_tag("2-big-screen.png", width:"940", alt:"2-big-screen.png", 
      								style: "margin-bottom: -2px;")%> 
    </div>
  </div>
  <div class="section" id="mobile">
    <div class="w-container">
      <h2 class="section-title">Sinapsis no se necesita instalar, está en tu navegador</h2>
      <p class="section-subtitle">Por que preocuparse de tener que instalaciones, compra de servidores, soporte, etc. Con Sinapsis eso no ocurrirá.</p>
      <div class="w-row">
        <div class="w-col w-col-6 center">
        <%= image_tag("3-responsive-color.png", width:"452")%>
        </div>
        <div class="w-col w-col-6 content-column">
        <%= image_tag("4-icon-chrome.png", width:"37px", class: 'grey-icon' )%>
        <%= image_tag("4-icon-fire.png", width:"37px", class: 'grey-icon' )%>
        <%= image_tag("4-icon-ie.png", width:"37px", class: 'grey-icon' )%>
        <%= image_tag("4-icon-safari.png", width:"37px", class: 'grey-icon' )%>
          <h3>En tu navegador favorito.</h3>
          <p>Sinapsis se puede utilizar en todos los navegadores, ya sea de equipos de escritorio, laptops, tablets, celulares.
            <br>Donde se tenga capacidad de conexión de Internet Sinapsis estará.&nbsp;</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section grey" id="features">
    <div class="w-container">
      <h2 class="section-title">¿Qué es Sinapsis?</h2>
      <p class="section-subtitle">La administración del equipo médico es siempre benéfica a tu organización.</p>
      <div class="w-row">
        <div class="w-col w-col-4">
          <div class="circle">
            <div class="number">1</div>
            <%= image_tag("desktop14.png", width:"256", class: 'frames' )%>
          </div>
          <h3>CMMS</h3>
          <p>Es un sistema para la gestión del equipo médico. Es un sistema computarizado para la administración de mantenimientos, que te permite mejorar o facilitar tu administración de tu equipo médico.</p>
        </div>
        <div class="w-col w-col-4">
          <div class="circle">
            <div class="number">2</div>
						<%= image_tag("medkit.png", width:"256", class: 'frames' )%>
          </div>
          <h3>¿En qué Ayuda?</h3>
          <p>El equipo médico es uno de los recursos donde mas se gasta dentro de los hospitales. Ademas tiene un papel sumamente importante para la atención a la salud de los pacientes.&nbsp;
            <br>Sinapsis te permitirá poder tener tu equipo médico en optimas condiciones para una atención ideal a sus pacientes.</p>
        </div>
        <div class="w-col w-col-4">
          <div class="circle">
            <div class="number">3</div>
            <%= image_tag("correct8.png", width:"256", class: 'frames' )%>
          </div>
          <h3>Ventajas</h3>
          <p>Te ayuda a almacenar la información que se va generando de tus equipos y poder tenerla cuando la requieres. Esto te ayuda a poder tomar decisiones acerca de nuevas adquisiciones o de que hacer con los equipos que tienes. La información siempre es valiosa.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="section centered">
    <div class="w-container">
      <h2 class="section-title">¿Por qué utilizar Sinapsis?</h2>
      <p class="section-subtitle">Sinapsis tiene funciones que te ayudaran a mejorar tu gestión del equipo médico.</p>
      <div class="w-row">
        <div class="w-col w-col-4 w-col-small-4">
          <div class="icons">
          <%= image_tag("listing1.png", width:"64" )%>
          </div>
          <h3><span>Inventario</span></h3>
          <p>La Organización Mundial de la Salud, así como otros organizamos como el Consejo de Salud General,&nbsp;Joint Commission International, para sus acreditaciones pide contar con el inventario total de los equipos con los que cuenta su organización. Sinapsis le ayuda a poder generarlo y actualizarlo de una manera simple.</p>
        </div>
        <div class="w-col w-col-4 w-col-small-4">
          <div class="icons">
					<%= image_tag("hostpital.png", width:"128" )%>
          </div>
          <h3>Áreas</h3>
          <p>Las áreas de tu organización se pueden tener ordenadas y de esta manera ver que realiza cada área, donde se localiza en el hospital, que subáreas la componen.</p>
        </div>
        <div class="w-col w-col-4 w-col-small-4">
          <div class="icons">
          	<%= image_tag("stethoscope6.png", width:"128" )%>
          </div>
          <h3>Equipos Médicos</h3>
          <p>La información del equipo siempre es importante entre mas información tengas de tu equipo mejor. Como tipo de equipo, función del equipo, lugar donde se encuentra, marca, modelo.</p>
        </div>
      </div>
      <div class="w-row">
        <div class="w-col w-col-4 w-col-small-4">
          <div class="icons">
          <%= image_tag("telephone65.png", width:"128" )%>
          </div>
          <h3>Contacto</h3>
          <p>Sinapsis te permite ver la información de los encargados de las áreas del hospital para siempre tener a la mano una forma de contacto con las diferentes partes del hospital. Ya que es trabajo de todos el mantener el equipo en optimas condiciones.</p>
        </div>
        <div class="w-col w-col-4 w-col-small-4">
          <div class="icons">
          <%= image_tag("qrplanet.png", width:"128" )%>
          </div>
          <h3>Código QR</h3>
          <p>Sinapsis te permite generar las etiquetas que tendrán tus equipos médicos en inventario. Para poder saber a que área pertenece cada uno. Estas etiquetas contarán con un código QR, este te ayuda a ver la información de tu equipo simplemente escaneando con tu celular.</p>
        </div>
      </div>
    </div>
  </div>
  <footer class="section footer">
    <div class="w-container">
      <div class="w-row">
        <div class="w-col w-col-6">
          <div class="footer-text">
          	<%= image_tag("sinapsis-completo.png", width: "100px") %>
          </div>
        </div>
        <div class="w-col w-col-6 right-footer-col">
          <a class="w-inline-block social-icon" href="mailto:contacto@sinapsis-cmms.com">
          	<%= image_tag("14-social-email.png", width:"20" )%>
          </a>
          <a class="w-inline-block social-icon" href="http://www.twitter.com/sinapsiscmms" target="_blank">
          <%= image_tag("14-social-twitter.png", width:"20") %>
          </a>
        </div>
      </div>
    </div>
  </footer>

app/views/static_pages/noaccount.html.erb
<%= provide(:title, "Registro No Creado") %>
<div class="container">
  <div class="page-header">
    <h1>Cuenta cancelada</h1>
    <div class="progress">
      <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
      </div>
    </div>
  </div>


<div class="container">
  <div class="jumbotron" style="border-radius: 15px; padding: 1px 15px 15px 15px;">
    <div class="container" style="margin-top: 27px;">
      <p>Esperamos contar con su preferencia en otro momento. Por favor envienos un correo con los  
      problemas que tuvo para poder mejorar nuestro servicio</p>
    </div>
	</div>
</div>
</div>