config/routes.rb
Rails.application.routes.draw do

  get 'master/show'

  root              'static_pages#home'
  get     'about'      =>  'static_pages#about'
  get     'signup'     =>  'users#new'
  get     'login'      =>  'sessions#new'
  post    'login'      =>  'sessions#create'
  delete  'logout'     =>  'sessions#destroy'
  get     'noaccount'  =>  'static_pages#noaccount'
  get     'new_home'   =>  'new_static_pages#home'

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :equipment_type
  resources :brands
  resources :equipment
  resources :hospitals
  resources :subareas
  resources :areas
  resources :hospitals do
    resources :floors, only: [] do
      get :areas_select, on: :member
    end
    resources :areas, only: [] do
      get :subareas_select, on: :member
    end
    resources :floors do
      resources :areas
    end
    resources :areas
    resources :equipment do
      get 'label' => 'equipment#label'
    end
    resources :equipment_type
    resources :brands
    resources :areas do
      resources :contacts
      resources :subareas
    end
    resources :contacts
  end
  resources :plans, only: [:index]
  resources :master do
    resources :plans
    resources :accounts
  end
  resources :accounts
  resources :contacts
  resources :plans do
    resources :hospitals,  only: [ :new, :create ] do
      resources :users,     only: [ :new, :create ] do
        resources :accounts,  only: [ :new, :create ]
      end
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  belongs_to :hospital
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :subareas
	belongs_to :hospital
	has_one :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :equipment
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :area
	belongs_to :hospital

	def area_name
		area.name
	end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :equipment_type
	belongs_to :brand
	belongs_to :hospital
	belongs_to :subarea
	mount_uploader :image, ImageUploader

	def brand_name
		brand.name
	end

	def subarea_name
		subarea.name
	end

	def equipment_type_name
		equipment_type.name
	end

	def cuadro_basico
		equipment_type.cuadro_basico
	end

	def umdns
		equipment_type.umdns
	end

	def gmnd
		equipment_type.gmnd
	end
end

app/models/equipment_type.rb
class EquipmentType < ActiveRecord::Base
	has_many :equipment
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	has_one :account
	has_many :users
	has_many :equipments
	has_many :areas
	has_many :contacts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :account
end

app/models/subarea.rb
class Subarea < ActiveRecord::Base
	belongs_to :area
	has_many :equipments

	def area_name
		area.name
	end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token
  before_save :downcase_email
  belongs_to :account
  belongs_to :hospital
  before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  												                        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, remember_token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :correct_user, only: [:show, :edit, :update]
  before_action :master_user, only: [:index]

  def show
  	@user = User.find(params[:id])
    if master_user?
      redirect_to master_path(@user)
    else
      @equipments = Equipment.where(hospital_id: current_hospital.id).last(5)
      @areas = Area.where(hospital_id: current_hospital.id).last(5)
      @contacts = Contact.where(hospital_id: current_hospital).last(5)
    end
  end

  def edit
    @user = User.find(params[:id])
    @hospital = Hospital.find(current_hospital.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Usuario actualizado"
      redirect_to @user
   else
    render @user
   end
  end

  def index
    @users = User.where(user_type: "normal").includes(:hospital)
  end

  def new
    @user = User.new
    @hospital = Hospital.find(params[:hospital_id])
    render :layout => "home_layout"
  end

  def create
    @user = User.create(user_params)
    if @user
      redirect_to new_plan_hospital_user_account_path(params[:plan_id],params[:hospital_id], @user.id)
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation,
        :hospital_id, :user_type)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end     
  end

  def logged_in?
    !current_user.nil?    
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Porfavor inicie seción"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/subareas_helper.rb
module SubareasHelper

end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def master_user
		redirect_to(root_url) unless current_user.user_type == "master"
	end

	def master_user?
		current_user.user_type == "master"
	end
end

app/views/users/edit.html.erb
<%= provide(:title, "Usuario" ) %>
  <div class="page-header">
    <h2>
    	Edición <small><%=  @user.name %></small>
    </h2>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
  <div class="col-xs-13 col-md-9">
	  <div class="modal-body">
		 <h2 class="form-signin-heading">Teclee los datos</h2>
		  <%= form_for(@user)  do |f| %>
		    <%= render 'shared/error_messages', object: f.object %>
		    <%= f.text_field :name, class: "form-control", placeholder: "Nombre",
		                                            required: true, autofocus: true, style: "margin-bottom: 10px;" %>          
		    <%= f.text_field :email, class: "form-control", placeholder: "Email",
		                                            required: true, style: "margin-bottom: 10px;" %>
		    <%= f.password_field :password, class: "form-control", placeholder: "Contraseña",
		                                              required: true, style: "margin-bottom: 10px;" %>  
		    <%= f.password_field :password_confirmation, class: "form-control", 
		                                      placeholder: "Confirmación Contraseña", style: "margin-bottom: 10px;" %>  
		    <%= f.hidden_field :hospital_id, :value => @hospital.id %>
		     
		    </div>
	        <div class="modal-footer">
	          <%= f.submit "Guardar", class: "btn btn-primary" %>
	        </div>
		  <% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<%= provide(:title, "Usuarios") %>

<div class="page-header">
    <h2>Cuentas</h2>
</div>
<div class="jumbotron col-md-12" style="padding: 25px 0;">
  <div class="container col-md-12" style="margin-top: 0;">
    <table class="table table-striped table-responsive">
      <thead>
        <tr>
          <td>Hospital</td>
          <td>Usuario</td>
          <td>email</td>
          <td>account</td>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.hospital.name %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.hospital.account.id %></td>
            <td><%= user.hospital.account.activated %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/new.html.erb
<%= provide(:title, "Usuario Nuevo") %>
<div class="container" style="max-width: 970px">
<div class="page-header">
  <h1>Registro <small>Registro de usuario administrador</small></h1>
  <div class="progress">
    <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width: 75%">
    </div>
  </div>
</div>
  <%= form_for(@user, url:  plan_hospital_users_path, html: { class: "form-signin",
            style:"border-radius: 10px; background-color: #eeeeee; padding: 20px;" })  do |f| %>
    <%= render 'shared/error_messages', object: @user %>
    <h2 class="form-signin-heading">Teclee sus datos</h2>
    <%= f.text_field :name, class: "form-control", placeholder: "Nombre Completo",
                                              required: true, autofocus: true,
                                              style:"margin-bottom: 10px;"%>
    <%= f.text_field :email, class: "form-control", placeholder: "Email",
                                              required: true,
                                              style:"margin-bottom: 10px;" %>
    <%= f.password_field :password, class: "form-control", placeholder: "Contraseña",
                                              required: true,
                                              style:"margin-bottom: 10px;" %>
    <%= f.password_field :password_confirmation, class: "form-control",
                                      placeholder: "Confirmación Contraseña", required: true,
                                      style:"margin-bottom: 10px;" %>
    <%= f.hidden_field :hospital_id, :value => @hospital.id %>
    <%= f.hidden_field :user_type, :value => "normal" %>
    <%= f.submit "Guardar Datos", class: "btn btn-lg btn-primary btn-block" %>
  <% end %>

</div> <!-- /container -->

app/views/users/show.html.erb
<%= provide(:title, "Usuario" ) %>
  <div class="page-header">
    <h2>
    	Bienvenido <small><%=  @user.name %></small>
    	<%= link_to "Editar", edit_user_path(@user),
                  class: "btn pull-right", style: "margin-right: 21px; color: cornflowerblue;
                    margin-top: 10px;" %>
    </h2>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
    <!-- <div class="row">
  		<div class="col-xs-16 col-sm-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Mantenimietos<small> Proximós</small>
            </h3>
          </div>
          <div class="panel-body">

          </div>
      </div>
    </div> -->
  	<div class="row">
  		<div class="col-md-12">
  			<div class="col-md-6 col-sm-12">
  				<div class="panel panel-default">
  					<div class="panel-heading">
              <h3 class="panel-title">Equipos<small> Ultimos creados</small>
              <%= link_to "Nuevo", new_hospital_equipment_path(current_hospital),
                  class: "btn pull-right", style: "margin-right: -10px; color: cornflowerblue; margin-top: -7px;" %>
              </h3>
            </div>
            <div class="panel-body">
            	<% if @equipments.empty? %>
            		No hay equipos
            	<% else %>
              <div class="table-responsive">
								<table class="table table-hover" style="margin-bottom: 0px;">
									<thead>
										<tr>
											<th>Modelo</th>
											<th>Subárea</th>
										</tr>
									</thead>
									<tbody>
										<% @equipments.each do |equipment| %>
											<tr onclick="location.href='<%= hospital_equipment_path(current_hospital, equipment) %>'">
												<td><%= equipment.model %></td>
												<td><%= equipment.subarea_name %></td>
											</tr>
										<% end %>
									</tbody>
								</table>
              </div>
								<%= link_to "Todos", hospital_equipment_index_path(current_hospital), class: "btn pull-right" %>
							<% end %>
            </div>
  				</div>
  			</div>
  			<div class="col-md-6 col-sm-12">
  				<div class="panel panel-default">
  					<div class="panel-heading">
              <h3 class="panel-title">Áreas<small> Ultimas creadas</small>
              <%= link_to "Nueva", new_hospital_floor_area_path(@hospital, 1), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
              </h3>
            </div>
            <div class="panel-body">
							<% if @areas.empty? %>
								No hay áreas
							<% else %>
              <div class="table-responsive">
								<table class="table table-hover table-responsive" style="margin-bottom: 0px;">
									<thead>
										<tr>
											<th>Nombre</th>
											<th>Piso</th>
											<th>Contacto</th>
											<th>Telefono</th>
										</tr>
									</thead>
									<tbody>
										<% @areas.each do |area| %>
											<tr>
												<td onclick="location.href='<%= hospital_floor_area_path(current_hospital, area.floor, area) %>'">
													<%= area.name %>
												</td>
												<td onclick="location.href='<%= hospital_floor_area_path(current_hospital, area.floor, area) %>'">
													<%= area.floor %>
												</td>
												<% if area.contact.nil? %>
													<td>Sin contacto</td>
													<td><%= link_to "Nuevo", new_hospital_area_contact_path(area.hospital_id, area), :class => "btn", style: "color: cornflowerblue;" %></td>
												<% else %>
													<td><%= area.contact.name %></td>
													<td><%= area.contact.phone %></td>
												<% end %>
											</tr>
										<% end %>
									</tbody>
								</table>
              </div>
								<%= link_to "Todas", hospital_floors_path(current_hospital), class: "btn pull-right" %>
		        	<% end %>
		       	</div>
  				</div>
  			</div>
  		</div>
  	</div>
  </div>
 </div>