config/routes.rb
Rails.application.routes.draw do

  get 'master/show'

  root              'static_pages#home'
  get     'about'      =>  'static_pages#about'
  get     'signup'     =>  'users#new'
  get     'login'      =>  'sessions#new'
  post    'login'      =>  'sessions#create'
  delete  'logout'     =>  'sessions#destroy'
  get     'noaccount'  =>  'static_pages#noaccount'
  get     'new_home'   =>  'new_static_pages#home'

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :equipment_type
  resources :brands
  resources :equipment
  resources :hospitals
  resources :subareas
  resources :areas
  resources :hospitals do
    resources :floors, only: [] do
      get :areas_select, on: :member
    end
    resources :areas, only: [] do
      get :subareas_select, on: :member
    end
    resources :floors do
      resources :areas
    end
    resources :areas
    resources :equipment do
      get 'label' => 'equipment#label'
    end
    resources :equipment_type
    resources :brands
    resources :areas do
      resources :contacts
      resources :subareas
    end
    resources :contacts
  end
  resources :plans, only: [:index]
  resources :master do
    resources :plans
    resources :accounts
  end
  resources :accounts
  resources :contacts
  resources :plans do
    resources :hospitals,  only: [ :new, :create ] do
      resources :users,     only: [ :new, :create ] do
        resources :accounts,  only: [ :new, :create ]
      end
    end
  end

end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :subareas
	belongs_to :hospital
	has_one :contact
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :create, :new, :destroy, :index]
  before_action :correct_hospital, only: [:show, :edit, :update, :create, :new, :destroy, :index]
  before_action :area_limit, only: [:new]

  def new
  	@area = Area.new
  end

  def index
  	@hospital = Hospital.find(params[:hospital_id])
  	@floors = floors_hospital
  	@floor = params[:floor_id]
  	@areas = Area.where(hospital_id: params[:hospital_id]).where(floor: params[:floor_id])
  end

  def edit
  	@floors = floors_hospital
  	@floor = params[:floor_id]
  	@hospital = Hospital.find(params[:hospital_id])
  	@area = Area.find(params[:id])
  end

  def update
  	@area = Area.find(params[:id])
   if @area.update_attributes(area_params)
      flash[:success] = "Área actualizada"
      redirect_to hospital_floor_area_path(@area.hospital_id, @area.floor, @area)
   else
    render  edit_hospital_floor_area_path(@area.hospital_id, @area.floor, @area)
   end
  end

  def show
  	@hospital = Hospital.find(params[:hospital_id])
  	@floors = floors_hospital
  	@floor = params[:floor_id]
  	@areas = Area.where(hospital_id: params[:hospital_id]).where(floor: params[:floor_id])
  	@area = Area.find(params[:id])
  	@contact = @area.contact
  	@subareas = @area.subareas
  end

  def new
  	@floors = floors_hospital
  	@floor = params[:floor_id]
  	@hospital = Hospital.find(params[:hospital_id])
  	@area = Area.new
  end

  def subareas_select
  	@subarea = Subarea.new

  	if Integer(params[:id]) != 0
			@area = Area.find(params[:id])
			@areas = Area.where(floor: @area.floor).where(hospital_id: params[:hospital_id])
			@subareas = Subarea.where(area_id: params[:id])
		else
			@subareas = nil
		end

  	respond_to do |format|
			format.js
		end
  end

	def create
		@area = Area.new(area_params)
		respond_to do |format|
		  if @area.save
        current_hospital.areas_quantity = current_hospital.areas_quantity + 1
		    format.js {}
        format.html { redirect_to hospital_floor_area_path(@area.hospital_id, @area.floor, @area)}
		  else
		    format.html { render new_area_path }
        format.js {}
		  end
		end
    @floors = floors_hospital
		@areas = Area.where(floor: @area.floor).where(hospital_id: params[:hospital_id])
	end

  private
    def area_params
      params.require(:area).permit(:name, :description, :floor, :contact_id, :hospital_id)
    end

    def area_limit
      @current_hospital = current_hospital
      if @current_hospital.areas_quantity > @current_hospital.limit_areas
        flash[:danger] = "Limite de áreas alcanzado"
        redirect_to current_user
      end
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_areas.html.erb
<%= select_tag "area_id", options_from_collection_for_select(areas, "id", "name"), include_blank: true, class: 'chosen-select', data: {placeholder: 'Seleccione Área'} %>

app/views/areas/_new_area.html.erb
<div class="modal fade" id="AreaModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4 class="modal-title" id="myModalLabel">Nueva Área</h4>
        </div>
        <%= form_for(@area, remote: true, url: areas_path) do |t| %>
        <div class="modal-body">
            <h2 class="form-signin-heading">Teclee los datos</h2>
            <%= t.text_field :name, class: "form-control", placeholder: "Nombre con el que se conoce",
                                                required: true, autofocus: true, style: "margin-bottom: 10px;" %>
            <%= t.text_area :description, class: "form-control", placeholder: "Descripción breve de la función que realiza", style: "height: 145px; margin-bottom: 10px; "%>
            <%= t.select :floor, @floors.map{ |b| [b, b] },{ :include_blank => "Seleccione Piso"}, {class: "form-control"} %>
            <%= t.hidden_field :hospital_id, :value => hospital.id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= t.submit "Guardar", class: "btn btn-primary" %> 
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/areas/create.js.erb
$("#area").find(".chosen-container").remove();
$("#area").find("select").remove();
$('#AreaModal').modal('hide');
$('#AreaModal').on('hidden.bs.modal', function (e) {
  $('#AreaModal').remove();
})
$("<%= escape_javascript(render 'subareas/new_subarea', areas: @areas) %>").appendTo("#modal");
$("<%= escape_javascript(render 'areas/areas', areas: @areas) %>").appendTo("#area");
$('.chosen-select').chosen({allow_single_deselect: true, no_results_text: "Sin resultados", 
width: "100%", placeholder_text_single: 'Seleccione una opción'});
$("<%= escape_javascript(link_to 'Nueva Subárea', '#SubareaModal', :class => 'btn', 'data-toggle' => 'modal') %>").appendTo("#area");
$("<%= escape_javascript(render 'areas/new_area', hospital: current_hospital) %>").appendTo("#modal");

app/views/areas/edit.html.erb
<%= provide(:title, "Editar Area" ) %>
  <div class="page-header">
    <h1>
    	Editar Área
    </h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
		 <div class="col-xs-13 col-md-9"> 
			 <%= form_for(@area) do |t| %>
	        <div class="modal-body">
	            <h2 class="form-signin-heading">Teclee los datos</h2>
	            <%= t.text_field :name, class: "form-control", placeholder: "Nombre con el que se conoce",
	                                                required: true, autofocus: true, style: "margin-bottom: 10px;" %>
	            <%= t.text_area :description, class: "form-control", placeholder: "Descripción breve de la función que realiza", style: "height: 145px; margin-bottom: 10px; "%>
	            <%= t.select :floor, @floors.map{ |b| [b, b] },{ :include_blank => "Seleccione Piso"}, {class: "form-control"} %>
	            <%= t.hidden_field :hospital_id, :value =>  @hospital.id %>
	        </div>
	        <div class="modal-footer">
	          <%= t.submit "Guardar", class: "btn btn-primary" %> 
	        </div>
	      <% end %>
		 </div>
	</div>
</div>

app/views/areas/index.html.erb
<%= provide(:title, "Areas" ) %>
  <div class="page-header">
    <h1>
    	Áreas
    </h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
		<div class="row" id="areas_idex">
		  <div class="col-md-6 col-sm-12">
		  	<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Seleccione Piso</h3>
				  </div>
				  <div class="panel-body">
				  	<% @floors.each do |floor| %>
							<div class="btn-group" role="group" aria-label="...">
								<%= link_to "Piso #{floor}", hospital_floor_areas_path(@hospital, floor),
												class: "btn btn btn-default" %>
							</div>
						<% end %>
				  </div>
				</div>
			</div>
			<div class="col-md-6 col-sm-12">
		  	<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title">Seleccione Área
				    	<%= link_to "Nueva Área", new_hospital_floor_area_path(@hospital, @floor), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
				    </h3>
				  </div>
				  <div class="panel-body">
				  	<% @areas.each do |area| %>
							<div class="btn-group" role="group" aria-label="...">
								<%= link_to area.name, hospital_floor_area_path(@hospital, @floor, area),
												class: "btn btn btn-default" %>
							</div>
						<% end %>
						<% if @areas.empty? %>
							<div class="btn-group" role="group" aria-label="...">
								<h5>No hay áreas</h5>
							</div>
						<% end %>
				  </div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/areas/new.html.erb
<%= provide(:title, "Nueva Area" ) %>
  <div class="page-header">
    <h1>
    	Nueva Área
    </h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
		 <div class="col-xs-13 col-md-9"> 
			 <%= form_for(@area) do |t| %>
	        <div class="modal-body">
	            <h2 class="form-signin-heading">Teclee los datos</h2>
	            <%= t.text_field :name, class: "form-control", placeholder: "Nombre con el que se conoce",
	                                                required: true, autofocus: true, style: "margin-bottom: 10px;" %>
	            <%= t.text_area :description, class: "form-control", placeholder: "Descripción breve de la función que realiza", style: "height: 145px; margin-bottom: 10px; "%>
	            <%= t.select :floor, @floors.map{ |b| [b, b] },{ :include_blank => "Seleccione Piso"}, {class: "form-control"} %>
	            <%= t.hidden_field :hospital_id, :value =>  @hospital.id %>
	        </div>
	        <div class="modal-footer">
	          <%= t.submit "Guardar", class: "btn btn-primary" %> 
	        </div>
	      <% end %>
		 </div>
	</div>
</div>

app/views/areas/show.html.erb
<%= provide(:title, "Areas" ) %>
  <div class="page-header">
    <h1>
    	Área <small><%= @area.name %></small>
    </h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
		<div class="row" id="areas_idex">
			<div class="col-md-12">
			  <div class="col-md-6 col-sm-12">
			  	<div class="panel panel-default">
					  <div class="panel-heading">
					    <h3 class="panel-title">Seleccione Piso</h3>
					  </div>
					  <div class="panel-body">
					  	<% @floors.each do |floor| %>
								<div class="btn-group" role="group" aria-label="...">
									<%= link_to "Piso #{floor}", hospital_floor_areas_path(@hospital, floor),
													class: "btn btn btn-default" %>
								</div>
							<% end %>
					  </div>
					</div>
				</div>
				<div class="col-md-6 col-sm-12">
			  	<div class="panel panel-default">
					  <div class="panel-heading">
					    <h3 class="panel-title">Seleccione Área
					    <%= link_to "Nueva Área", new_hospital_floor_area_path(@hospital, @floor), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
					    </h3>
					  </div>
					  <div class="panel-body">
					  	<% @areas.each do |area| %>
								<div class="btn-group" role="group" aria-label="...">
									<%= link_to area.name, hospital_floor_area_path(@hospital, @floor, area),
													class: "btn btn btn-default" %>
								</div>
							<% end %>
					  </div>
					</div>
				</div>
			</div>
		</div>
		<div class="row" id="info_idex">
		  <div class="col-md-12">
				<div class="page-header">
          <h4 style="margin-left: 15px;">
          Información
          <%= link_to "Editar Área", edit_hospital_floor_area_path(@hospital, @floor, @area),
            class: "btn pull-right", style: "margin-top: -10px; color: cornflowerblue;margin-right: 10px;" %>
          </h4>
        </div>
				  	<div class="col-md-12">
					  	<div class="panel panel-default">
							  <div class="panel-heading">
							    <h3 class="panel-title">Descripción</h3>
							  </div>
							  <div class="panel-body">
							  	<%= @area.description %>
							  </div>
							</div>
						</div>
						<div class="col-md-6 col-sm-12">
					  	<div class="panel panel-default">
							  <div class="panel-heading">
							    <h3 class="panel-title">Contacto
							    <% if @contact.nil? %>
							    	<%= link_to "Nuevo Contacto", new_hospital_area_contact_path(@hospital, @area), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
							    <% else %>
							    	<%= link_to "Editar Contacto", edit_hospital_area_contact_path(@hospital, @area, @contact), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
							    <% end %>
							    </h3>
							  </div>
							  <div class="panel-body">
							  	<% if !@contact.nil? %>
							  	<ul>
						  			<li><strong>Nombre: </strong><%= @contact.name %></li>
						  			<li><strong>Email: </strong><%= @contact.email %></li>
						  			<li><strong>Telefono: </strong><%= @contact.phone %></li>
							  	</ul>
							  	<% else %>
							  		Sin Contacto
							  	<% end %>
							  </div>
							</div>
						</div>
						<div class="col-md-6 col-sm-12">
					  	<div class="panel panel-default">
							  <div class="panel-heading">
							    <h3 class="panel-title">Subáreas
							    <%= link_to "Nueva Subáreas", new_hospital_area_subarea_path(@hospital, @area), :class => "btn pull-right", style: "margin-top: -8px; color: cornflowerblue;" %>
							    </h3>
							  </div>
							  <div class="panel-body">
							  	<% if !@subareas.empty? %>
							  		<table style="width: 100%;" class="table-responsive">
							  			<thead>
							  				<tr>
							  					<th>Nombre</th>
                          <th></th>
							  					<th>Editar</th>
							  					<th>Borrar</th>
							  				</tr>
							  			</thead>
							  			<tbody>
								  			<% @subareas.each do |subarea| %>
									  			<tr>
									  				<td><%= subarea.name %></td>
                            <td><%= link_to "Ver equipos",hospital_area_subarea_path(@hospital, @area, subarea) %></td>
									  				<td><%= link_to '<i class="fa fa-cog">
                            </i>'.html_safe, edit_hospital_area_subarea_path(@hospital, @area, subarea) %></td>
									  				<td><%= link_to '<i class="fa fa-times">
                                                </i>'.html_safe, subarea, method: :delete,
                                                data: { confirm: "¿Estas seguro?" },
                                                title: subarea.name %></td>
									  			</tr>
								  			<% end %>
								  		</tbody>
							  		</table>
							  	<% else %>
							  		No hay subáreas
							  	<% end %>
							  </div>
							</div>
						</div>
			</div>
		</div>
	</div>
</div>

app/views/areas/subareas.js.erb
$("#subarea").find(".chosen-container").remove();
$("#subarea").find("select").remove();
$("#modal").find("#new_subarea_modal").remove();
<% if !@subareas.nil? %>
	$("<%= escape_javascript(render 'subareas/subareas', subareas: @subareas) %>").appendTo("#subarea");
	$('.chosen-select').chosen({allow_single_deselect: true, no_results_text: "Sin resultados", 
	width: "100%", placeholder_text_single: 'Seleccione una opción'});
	$("<%= escape_javascript(render 'subareas/new_subarea', areas: @areas) %>").appendTo("#modal");
<% end %>

app/views/areas/subareas_index.js.erb
<% if !@subareas.nil? %>
	$("<%= escape_javascript(render 'subareas/subareas', subareas: @subareas) %>").appendTo("#subareas_show");
	$('.chosen-select').chosen({allow_single_deselect: true, no_results_text: "Sin resultados", 
	width: "100%", placeholder_text_single: 'Seleccione una opción'});
<% end %>

app/views/areas/subareas_select.js.erb
$("#subarea").find(".chosen-container").remove();
$("#subarea").find("select").remove();
$("#modal").find("#new_subarea_modal").remove();
<% if !@subareas.nil? %>
	$("<%= escape_javascript(render 'subareas/subareas', subareas: @subareas) %>").appendTo("#subarea");
	$('.chosen-select').chosen({allow_single_deselect: true, no_results_text: "Sin resultados", 
	width: "100%", placeholder_text_single: 'Seleccione una opción'});
	$("<%= escape_javascript(render 'subareas/new_subarea', areas: @areas) %>").appendTo("#modal");
<% end %>