config/routes.rb
Rails.application.routes.draw do

  get 'master/show'

  root              'static_pages#home'
  get     'about'      =>  'static_pages#about'
  get     'signup'     =>  'users#new'
  get     'login'      =>  'sessions#new'
  post    'login'      =>  'sessions#create'
  delete  'logout'     =>  'sessions#destroy'
  get     'noaccount'  =>  'static_pages#noaccount'
  get     'new_home'   =>  'new_static_pages#home'

  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :equipment_type
  resources :brands
  resources :equipment
  resources :hospitals
  resources :subareas
  resources :areas
  resources :hospitals do
    resources :floors, only: [] do
      get :areas_select, on: :member
    end
    resources :areas, only: [] do
      get :subareas_select, on: :member
    end
    resources :floors do
      resources :areas
    end
    resources :areas
    resources :equipment do
      get 'label' => 'equipment#label'
    end
    resources :equipment_type
    resources :brands
    resources :areas do
      resources :contacts
      resources :subareas
    end
    resources :contacts
  end
  resources :plans, only: [:index]
  resources :master do
    resources :plans
    resources :accounts
  end
  resources :accounts
  resources :contacts
  resources :plans do
    resources :hospitals,  only: [ :new, :create ] do
      resources :users,     only: [ :new, :create ] do
        resources :accounts,  only: [ :new, :create ]
      end
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :user
  belongs_to :plan
  belongs_to :hospital
end

app/models/area.rb
class Area < ActiveRecord::Base
	has_many :subareas
	belongs_to :hospital
	has_one :contact
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :equipment
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :area
	belongs_to :hospital

	def area_name
		area.name
	end

end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :equipment_type
	belongs_to :brand
	belongs_to :hospital
	belongs_to :subarea
	mount_uploader :image, ImageUploader

	def brand_name
		brand.name
	end

	def subarea_name
		subarea.name
	end

	def equipment_type_name
		equipment_type.name
	end

	def cuadro_basico
		equipment_type.cuadro_basico
	end

	def umdns
		equipment_type.umdns
	end

	def gmnd
		equipment_type.gmnd
	end
end

app/models/equipment_type.rb
class EquipmentType < ActiveRecord::Base
	has_many :equipment
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base
	has_one :account
	has_many :users
	has_many :equipments
	has_many :areas
	has_many :contacts
end

app/models/plan.rb
class Plan < ActiveRecord::Base
	belongs_to :account
end

app/models/subarea.rb
class Subarea < ActiveRecord::Base
	belongs_to :area
	has_many :equipments

	def area_name
		area.name
	end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :reset_token
  before_save :downcase_email
  belongs_to :account
  belongs_to :hospital
  before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }


  def User.digest(string)
  	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
  												                        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, remember_token)
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  private

    def downcase_email
      self.email = email.downcase
    end
    
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :master_user, only: [:new, :edit, :create]

  def new
  	@plan = Plan.new
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(plan_params)
      flash[:success] = "Plan actualizado"
      redirect_to @plan
   else
    render  edit_plan_path(@plan)
   end
  end

  def show
    @plan = Plan.find(params[:id])    
  end

  def create
  	 @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to plans_path
    else
      render 'new'
    end
  end

  def index
    @plans = Plan.all
    if !logged_in?
      render :layout => "home_layout"
    end
  end

  private

    def plan_params
      params.require(:plan).permit(:name, :cost, :description, :max_equipment, :max_area )
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end     
  end

  def logged_in?
    !current_user.nil?    
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Porfavor inicie seción"
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/subareas_helper.rb
module SubareasHelper

end

app/helpers/supplier_helper.rb
module SupplierHelper
end

app/helpers/users_helper.rb
module UsersHelper
	
	def master_user
		redirect_to(root_url) unless current_user.user_type == "master"
	end

	def master_user?
		current_user.user_type == "master"
	end
end

app/views/plans/_index_activation.html.erb
  <%= provide(:title, "Plan") %>
<div class="container" style="max-width: 1120px">
  <div>
    <div class="page-header">
      <h1>Registro <small>Tipo de Plan</small></h1>
      <div class="progress">
        <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="width: 25%">
        </div>
      </div>
    </div>
  </div>
  <div>
    <div class="row">
      <% @plans.each do |plan| %>
        <div class="col-md-3">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h4 class="text-center"><%= plan.name %></h4>
            </div>
            <div class="panel-body">
              <p class="lead text-center">
                <strong>
                <%= number_to_currency(plan.cost, :unit => "$") %>/año
                </strong>
              </p>
              <%= markdown(plan.description) %>
            </div>
            <div class="panel-footer">
            <% #Plan 1 plan mas bajo %>
              <%= link_to "Elegir", new_plan_hospital_path(plan.id), 
                                class: "btn btn-lg btn-block btn-success" %> 
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="page-header">
      <h3>Nota</h3>
    </div>
    <div>
      <ul>
        <li>Cantidades en Pesos Mexicanos.</li>
        <li>Precios preferenciales por confiar en nosotros en nuesto inicio.</li>
        <li>Al registrarse se le enviara un correo con la información de pago.</li>
        <li>Se tiene un tiempo de gracia para realizar el pago.</li>
        <li>Precios No incluyen IVA</li>
      </ul>
    </div>
  </div>
</div>

app/views/plans/_index_master.html.erb
<%= provide(:title, "Plan") %>
  <div class="page-header">
    <h1>Planes <small>Tipo de Plan</small></h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
    <div class="col-xs-13 col-md-9"> 
      <div class="row">
        <% @plans.each do |plan| %>
          <div class="col-md-4">
            <div class="panel panel-success">
              <div class="panel-heading">
                <h4 class="text-center"><%= plan.name %></h4>
              </div>
              <div class="panel-body text-center">
                <p class="lead">
                  <strong><%= number_to_currency(plan.cost, :unit => "$") %>/anual</strong>
                </p>
              </div>
              <ul class="list-group list-group-flush text-center">
              <%= markdown(plan.description) %>
              </ul>
              <div class="panel-footer">
              <% #Plan 1 plan mas bajo %>
                <%= link_to "Editar", edit_master_plan_path(current_user, plan.id), 
                                  class: "btn btn-lg btn-block btn-success" %> 
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plans/edit.html.erb
<%= provide(:title, "Plan") %>
  <div class="page-header">
    <h1>Editar Plan <small>Datos</small></h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
    <div class="col-xs-13 col-md-9"> 
      <%= form_for(@plan)  do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <h2 class="form-signin-heading">Teclee datos del plan</h2>
        <%= f.text_field :name, class: "form-control", placeholder: "Nombre",
                                                  required: true, autofocus: true, style: "margin-bottom: 10px" %>
        <%= f.text_field :cost, class: "form-control", placeholder: "Costo",
                                                  required: true, style: "margin-bottom: 10px" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Descripción",
                                                  required: true, 
                                                  style: "height: 145px; margin-bottom: 10px"%>
        <%= f.text_field :max_equipment, class: "form-control", placeholder: "Maximos equipos",
                                                  required: true, style: "margin-bottom: 10px" %>
        <%= f.text_field :max_area, class: "form-control", placeholder: "Maximo Áreas",
                                                  required: true, style: "margin-bottom: 10px" %>                                  
        <%= f.submit "Guardar Plan", class: "btn btn-primary" %> 
      <% end %>
    </div>
  </div>
</div>

app/views/plans/index.html.erb
<% if logged_in? && master_user? %>
  <%= render 'plans/index_master' %>
<% else %>
  <%= render 'plans/index_activation' %>
<% end %>

app/views/plans/new.html.erb
<%= provide(:title, "Plan") %>
  <div class="page-header">
    <h1>Nuevo Plan <small>Datos</small></h1>
  </div>
<div class="jumbotron" style="padding: 25px 0;">
  <div class="container" style="margin-top: 0;">
    <div class="col-xs-13 col-md-9"> 
      <%= form_for(@plan)  do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <h2 class="form-signin-heading">Teclee datos del plan</h2>
        <%= f.text_field :name, class: "form-control", placeholder: "Nombre",
                                                  required: true, autofocus: true, style: "margin-bottom: 10px" %>
        <%= f.text_field :cost, class: "form-control", placeholder: "Costo",
                                                  required: true, style: "margin-bottom: 10px" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Descripción",
                                                  required: true, 
                                                  style: "height: 145px; margin-bottom: 10px"%>
        <%= f.text_field :max_equipment, class: "form-control", placeholder: "Maximos equipos",
                                                  required: true, style: "margin-bottom: 10px" %>
        <%= f.text_field :max_area, class: "form-control", placeholder: "Maximo Áreas",
                                                  required: true, style: "margin-bottom: 10px" %>                                  
        <%= f.submit "Guardar Plan", class: "btn btn-primary" %> 
      <% end %>
    </div>
  </div>
</div>